name: ReUsableBuildCodeFromOtherRepo

on:
  # Allows you to run this workflow when triggered by another workflow
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
    secrets:
      PATTOKEN:
        required: true


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: check
          token: ${{ secrets.PATTOKEN }}

      - name: ECHO Readme
        run: cat README.md

      - name: Build with Maven
        run: mvn clean install
