name: ReUsable

on:
  # Triggers the workflow on call from the source repo.
  workflow_call:
    inputs:
      user:
        required: true
        type: string
      registry:
        required: true
        type: string
    secrets:
      PATTOKEN:
        required: true


env:
  REGISTRY: ${{ inputs.registry }}
  user: ${{ inputs.user }}

jobs:
  
  build:
    
    runs-on: ubuntu-20.04

    permissions:
      contents: 'read'
      packages: 'write'

    steps:
    
    - name: Check User with inputs
      run: |
        echo Registry = ${{ inputs.registry }}
        echo user = ${{ inputs.user }}
        
    - name: Check User with env
      run: |
        echo Registry = ${{ env.REGISTRY }}
        echo user = ${{ env.user }}
        
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.user}}
        password: ${{ secrets.GITHUB_TOKEN }} #${{ secrets.PATTOKEN }}
